// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/rollapp/sequencers/types/tx.proto

package sequencers

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateRewardAddress struct {
	// Operator is the bech32-encoded address of the actor sending the update
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// RewardAddr is a bech32 encoded sdk acc address
	RewardAddr string `protobuf:"bytes,2,opt,name=reward_addr,json=rewardAddr,proto3" json:"reward_addr,omitempty"`
}

func (m *MsgUpdateRewardAddress) Reset()         { *m = MsgUpdateRewardAddress{} }
func (m *MsgUpdateRewardAddress) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRewardAddress) ProtoMessage()    {}
func (*MsgUpdateRewardAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{0}
}
func (m *MsgUpdateRewardAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRewardAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRewardAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRewardAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRewardAddress.Merge(m, src)
}
func (m *MsgUpdateRewardAddress) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRewardAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRewardAddress.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRewardAddress proto.InternalMessageInfo

func (m *MsgUpdateRewardAddress) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgUpdateRewardAddress) GetRewardAddr() string {
	if m != nil {
		return m.RewardAddr
	}
	return ""
}

type MsgUpdateRewardAddressResponse struct {
}

func (m *MsgUpdateRewardAddressResponse) Reset()         { *m = MsgUpdateRewardAddressResponse{} }
func (m *MsgUpdateRewardAddressResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateRewardAddressResponse) ProtoMessage()    {}
func (*MsgUpdateRewardAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{1}
}
func (m *MsgUpdateRewardAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateRewardAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateRewardAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateRewardAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateRewardAddressResponse.Merge(m, src)
}
func (m *MsgUpdateRewardAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateRewardAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateRewardAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateRewardAddressResponse proto.InternalMessageInfo

type MsgUpdateWhitelistedRelayers struct {
	// Operator is the bech32-encoded address of the actor sending the update
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// Relayers is an array of the whitelisted relayer addresses. Addresses are bech32-encoded strings.
	Relayers []string `protobuf:"bytes,2,rep,name=relayers,proto3" json:"relayers,omitempty"`
}

func (m *MsgUpdateWhitelistedRelayers) Reset()         { *m = MsgUpdateWhitelistedRelayers{} }
func (m *MsgUpdateWhitelistedRelayers) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateWhitelistedRelayers) ProtoMessage()    {}
func (*MsgUpdateWhitelistedRelayers) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{2}
}
func (m *MsgUpdateWhitelistedRelayers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateWhitelistedRelayers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateWhitelistedRelayers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateWhitelistedRelayers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateWhitelistedRelayers.Merge(m, src)
}
func (m *MsgUpdateWhitelistedRelayers) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateWhitelistedRelayers) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateWhitelistedRelayers.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateWhitelistedRelayers proto.InternalMessageInfo

func (m *MsgUpdateWhitelistedRelayers) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgUpdateWhitelistedRelayers) GetRelayers() []string {
	if m != nil {
		return m.Relayers
	}
	return nil
}

type MsgUpdateWhitelistedRelayersResponse struct {
}

func (m *MsgUpdateWhitelistedRelayersResponse) Reset()         { *m = MsgUpdateWhitelistedRelayersResponse{} }
func (m *MsgUpdateWhitelistedRelayersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateWhitelistedRelayersResponse) ProtoMessage()    {}
func (*MsgUpdateWhitelistedRelayersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{3}
}
func (m *MsgUpdateWhitelistedRelayersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateWhitelistedRelayersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateWhitelistedRelayersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateWhitelistedRelayersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateWhitelistedRelayersResponse.Merge(m, src)
}
func (m *MsgUpdateWhitelistedRelayersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateWhitelistedRelayersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateWhitelistedRelayersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateWhitelistedRelayersResponse proto.InternalMessageInfo

// ConsensusMsgUpsertSequencer is a consensus message to upsert the sequencer.
type ConsensusMsgUpsertSequencer struct {
	// Signer is the bech32-encoded address of the consensus msg signer.
	// Expected to be an authorized address.
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	// Operator is the bech32-encoded address of the sequencer
	Operator string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	// ConsPubKey is a tendermint consensus pub key of the sequencer.
	// NB! google.protobuf.Any MUST NOT hold any values from the current
	// package (dymension_rdk.sequencers.types). Otherwise, it will lead to proto wiring error.
	ConsPubKey *types.Any `protobuf:"bytes,3,opt,name=cons_pub_key,json=consPubKey,proto3" json:"cons_pub_key,omitempty"`
	// RewardAddr is the bech32-encoded sequencer's reward address
	RewardAddr string `protobuf:"bytes,4,opt,name=reward_addr,json=rewardAddr,proto3" json:"reward_addr,omitempty"`
	// Relayers is an array of the whitelisted relayer addresses of the sequencer.
	// Addresses are bech32-encoded strings.
	Relayers []string `protobuf:"bytes,5,rep,name=relayers,proto3" json:"relayers,omitempty"`
}

func (m *ConsensusMsgUpsertSequencer) Reset()         { *m = ConsensusMsgUpsertSequencer{} }
func (m *ConsensusMsgUpsertSequencer) String() string { return proto.CompactTextString(m) }
func (*ConsensusMsgUpsertSequencer) ProtoMessage()    {}
func (*ConsensusMsgUpsertSequencer) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{4}
}
func (m *ConsensusMsgUpsertSequencer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsensusMsgUpsertSequencer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsensusMsgUpsertSequencer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsensusMsgUpsertSequencer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusMsgUpsertSequencer.Merge(m, src)
}
func (m *ConsensusMsgUpsertSequencer) XXX_Size() int {
	return m.Size()
}
func (m *ConsensusMsgUpsertSequencer) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusMsgUpsertSequencer.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusMsgUpsertSequencer proto.InternalMessageInfo

func (m *ConsensusMsgUpsertSequencer) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *ConsensusMsgUpsertSequencer) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ConsensusMsgUpsertSequencer) GetConsPubKey() *types.Any {
	if m != nil {
		return m.ConsPubKey
	}
	return nil
}

func (m *ConsensusMsgUpsertSequencer) GetRewardAddr() string {
	if m != nil {
		return m.RewardAddr
	}
	return ""
}

func (m *ConsensusMsgUpsertSequencer) GetRelayers() []string {
	if m != nil {
		return m.Relayers
	}
	return nil
}

type ConsensusMsgUpsertSequencerResponse struct {
}

func (m *ConsensusMsgUpsertSequencerResponse) Reset()         { *m = ConsensusMsgUpsertSequencerResponse{} }
func (m *ConsensusMsgUpsertSequencerResponse) String() string { return proto.CompactTextString(m) }
func (*ConsensusMsgUpsertSequencerResponse) ProtoMessage()    {}
func (*ConsensusMsgUpsertSequencerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{5}
}
func (m *ConsensusMsgUpsertSequencerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsensusMsgUpsertSequencerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsensusMsgUpsertSequencerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsensusMsgUpsertSequencerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusMsgUpsertSequencerResponse.Merge(m, src)
}
func (m *ConsensusMsgUpsertSequencerResponse) XXX_Size() int {
	return m.Size()
}
func (m *ConsensusMsgUpsertSequencerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusMsgUpsertSequencerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusMsgUpsertSequencerResponse proto.InternalMessageInfo

type MsgBumpAccountSequences struct {
	// authority defines the address of the authority that is allowed to bump the account sequences.
	// this is gov but it can be triggered by a consensus message.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgBumpAccountSequences) Reset()         { *m = MsgBumpAccountSequences{} }
func (m *MsgBumpAccountSequences) String() string { return proto.CompactTextString(m) }
func (*MsgBumpAccountSequences) ProtoMessage()    {}
func (*MsgBumpAccountSequences) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{6}
}
func (m *MsgBumpAccountSequences) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBumpAccountSequences) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBumpAccountSequences.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBumpAccountSequences) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBumpAccountSequences.Merge(m, src)
}
func (m *MsgBumpAccountSequences) XXX_Size() int {
	return m.Size()
}
func (m *MsgBumpAccountSequences) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBumpAccountSequences.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBumpAccountSequences proto.InternalMessageInfo

func (m *MsgBumpAccountSequences) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

type MsgBumpAccountSequencesResponse struct {
}

func (m *MsgBumpAccountSequencesResponse) Reset()         { *m = MsgBumpAccountSequencesResponse{} }
func (m *MsgBumpAccountSequencesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBumpAccountSequencesResponse) ProtoMessage()    {}
func (*MsgBumpAccountSequencesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{7}
}
func (m *MsgBumpAccountSequencesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBumpAccountSequencesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBumpAccountSequencesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBumpAccountSequencesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBumpAccountSequencesResponse.Merge(m, src)
}
func (m *MsgBumpAccountSequencesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBumpAccountSequencesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBumpAccountSequencesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBumpAccountSequencesResponse proto.InternalMessageInfo

type MsgUpgradeDRS struct {
	// authority defines the address of the authority that is allowed to bump the account sequences.
	// this is gov but it can be triggered by a consensus message.
	Authority  string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	DrsVersion uint64 `protobuf:"varint,2,opt,name=drs_version,json=drsVersion,proto3" json:"drs_version,omitempty"`
}

func (m *MsgUpgradeDRS) Reset()         { *m = MsgUpgradeDRS{} }
func (m *MsgUpgradeDRS) String() string { return proto.CompactTextString(m) }
func (*MsgUpgradeDRS) ProtoMessage()    {}
func (*MsgUpgradeDRS) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{8}
}
func (m *MsgUpgradeDRS) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpgradeDRS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpgradeDRS.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpgradeDRS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpgradeDRS.Merge(m, src)
}
func (m *MsgUpgradeDRS) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpgradeDRS) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpgradeDRS.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpgradeDRS proto.InternalMessageInfo

func (m *MsgUpgradeDRS) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpgradeDRS) GetDrsVersion() uint64 {
	if m != nil {
		return m.DrsVersion
	}
	return 0
}

type MsgUpgradeDRSResponse struct {
}

func (m *MsgUpgradeDRSResponse) Reset()         { *m = MsgUpgradeDRSResponse{} }
func (m *MsgUpgradeDRSResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpgradeDRSResponse) ProtoMessage()    {}
func (*MsgUpgradeDRSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb27942d1c1a6ff0, []int{9}
}
func (m *MsgUpgradeDRSResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpgradeDRSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpgradeDRSResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpgradeDRSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpgradeDRSResponse.Merge(m, src)
}
func (m *MsgUpgradeDRSResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpgradeDRSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpgradeDRSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpgradeDRSResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateRewardAddress)(nil), "dymension_rdk.sequencers.types.MsgUpdateRewardAddress")
	proto.RegisterType((*MsgUpdateRewardAddressResponse)(nil), "dymension_rdk.sequencers.types.MsgUpdateRewardAddressResponse")
	proto.RegisterType((*MsgUpdateWhitelistedRelayers)(nil), "dymension_rdk.sequencers.types.MsgUpdateWhitelistedRelayers")
	proto.RegisterType((*MsgUpdateWhitelistedRelayersResponse)(nil), "dymension_rdk.sequencers.types.MsgUpdateWhitelistedRelayersResponse")
	proto.RegisterType((*ConsensusMsgUpsertSequencer)(nil), "dymension_rdk.sequencers.types.ConsensusMsgUpsertSequencer")
	proto.RegisterType((*ConsensusMsgUpsertSequencerResponse)(nil), "dymension_rdk.sequencers.types.ConsensusMsgUpsertSequencerResponse")
	proto.RegisterType((*MsgBumpAccountSequences)(nil), "dymension_rdk.sequencers.types.MsgBumpAccountSequences")
	proto.RegisterType((*MsgBumpAccountSequencesResponse)(nil), "dymension_rdk.sequencers.types.MsgBumpAccountSequencesResponse")
	proto.RegisterType((*MsgUpgradeDRS)(nil), "dymension_rdk.sequencers.types.MsgUpgradeDRS")
	proto.RegisterType((*MsgUpgradeDRSResponse)(nil), "dymension_rdk.sequencers.types.MsgUpgradeDRSResponse")
}

func init() {
	proto.RegisterFile("types/rollapp/sequencers/types/tx.proto", fileDescriptor_bb27942d1c1a6ff0)
}

var fileDescriptor_bb27942d1c1a6ff0 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xd3, 0x52, 0xb5, 0x13, 0xca, 0x21, 0x2a, 0x6d, 0x08, 0xc5, 0x0d, 0xe1, 0xab, 0xe2,
	0x60, 0x0b, 0x90, 0x38, 0xe4, 0x96, 0x82, 0xc4, 0x01, 0x55, 0x42, 0x2e, 0x1f, 0x12, 0x07, 0x22,
	0xdb, 0x3b, 0x6c, 0xac, 0x26, 0xbb, 0xcb, 0xce, 0xba, 0xd4, 0x1c, 0xf9, 0x05, 0xfc, 0x14, 0x7e,
	0x06, 0xc7, 0x4a, 0x5c, 0x38, 0xa2, 0xe4, 0xc0, 0xdf, 0x40, 0x6b, 0x3b, 0x8e, 0x12, 0x4a, 0x4e,
	0xf6, 0xdb, 0x79, 0xbb, 0xef, 0xbd, 0x19, 0x0d, 0x3c, 0x30, 0x99, 0x42, 0xf2, 0xb5, 0x1c, 0x8d,
	0x42, 0xa5, 0x7c, 0xc2, 0x4f, 0x29, 0x8a, 0x18, 0x35, 0xf9, 0x45, 0xc1, 0x9c, 0x7b, 0x4a, 0x4b,
	0x23, 0x9b, 0x2e, 0xcb, 0xc6, 0x28, 0x28, 0x91, 0x62, 0xa0, 0xd9, 0xa9, 0x37, 0x27, 0x7a, 0x39,
	0xb1, 0xbd, 0xc3, 0x25, 0x97, 0x39, 0xd5, 0xb7, 0x7f, 0xc5, 0xad, 0xf6, 0xad, 0xe2, 0x95, 0x58,
	0xd2, 0x58, 0x92, 0x3f, 0x26, 0xee, 0x9f, 0x3d, 0xb2, 0x9f, 0xb2, 0x7c, 0x83, 0x4b, 0xc9, 0x47,
	0xe8, 0xe7, 0x28, 0x4a, 0x3f, 0xfa, 0xa1, 0xc8, 0x8a, 0x52, 0x97, 0xc1, 0xee, 0x31, 0xf1, 0x37,
	0x8a, 0x85, 0x06, 0x03, 0xfc, 0x1c, 0x6a, 0xd6, 0x67, 0x4c, 0x23, 0x51, 0xb3, 0x0d, 0x9b, 0x52,
	0xa1, 0x0e, 0x8d, 0xd4, 0x2d, 0xa7, 0xe3, 0x1c, 0x6e, 0x05, 0x15, 0x6e, 0x1e, 0x40, 0x43, 0xe7,
	0xe4, 0x41, 0xc8, 0x98, 0x6e, 0xd5, 0xf3, 0x32, 0xe8, 0xea, 0x7e, 0x6f, 0xfb, 0xeb, 0x9f, 0xef,
	0x0f, 0x2b, 0x7e, 0xb7, 0x03, 0xee, 0xe5, 0x2a, 0x01, 0x92, 0x92, 0x82, 0xb0, 0x8b, 0xb0, 0x5f,
	0x31, 0xde, 0x0d, 0x13, 0x83, 0xa3, 0x84, 0x0c, 0xb2, 0x00, 0x47, 0x61, 0x86, 0x7a, 0xb5, 0x9b,
	0x36, 0x6c, 0xea, 0x92, 0xd7, 0xaa, 0x77, 0xd6, 0x6c, 0x6d, 0x86, 0x97, 0x8d, 0xdc, 0x87, 0xbb,
	0xab, 0x64, 0x2a, 0x3b, 0x3f, 0x1d, 0xb8, 0xf9, 0xcc, 0xfe, 0x09, 0x4a, 0x29, 0xbf, 0x41, 0xa8,
	0xcd, 0xc9, 0x6c, 0x1a, 0xcd, 0x5d, 0xd8, 0xa0, 0x84, 0x0b, 0x9c, 0x99, 0x29, 0xd1, 0x82, 0xcd,
	0xfa, 0x92, 0xcd, 0xa7, 0x70, 0x35, 0x96, 0x82, 0x06, 0x2a, 0x8d, 0x06, 0xa7, 0x98, 0xb5, 0xd6,
	0x3a, 0xce, 0x61, 0xe3, 0xf1, 0x8e, 0x57, 0x0c, 0xc7, 0x9b, 0x0d, 0xc7, 0xeb, 0x8b, 0x2c, 0x00,
	0xcb, 0x7c, 0x95, 0x46, 0x2f, 0x31, 0x5b, 0x6e, 0xf6, 0xfa, 0x72, 0xb3, 0x17, 0xf2, 0x5f, 0x59,
	0xca, 0xdf, 0xb0, 0xf9, 0x4b, 0x77, 0xdd, 0x7b, 0x70, 0x67, 0x45, 0xa8, 0x2a, 0xfc, 0x0b, 0xd8,
	0x3b, 0x26, 0x7e, 0x94, 0x8e, 0x55, 0x3f, 0x8e, 0x65, 0x2a, 0x2a, 0x0a, 0x35, 0xf7, 0x61, 0x2b,
	0x4c, 0xcd, 0x50, 0xea, 0xc4, 0x64, 0x65, 0xf4, 0xf9, 0x41, 0xef, 0x9a, 0x15, 0x9b, 0xe3, 0xee,
	0x6d, 0x38, 0xf8, 0xcf, 0x43, 0x95, 0xd6, 0x07, 0xd8, 0xce, 0x9d, 0x70, 0x1d, 0x32, 0x7c, 0x1e,
	0x9c, 0xac, 0x56, 0xb0, 0xbd, 0x60, 0x9a, 0x06, 0x67, 0xa8, 0xed, 0x8a, 0xe4, 0x2d, 0x5e, 0x0f,
	0x80, 0x69, 0x7a, 0x5b, 0x9c, 0xfc, 0x63, 0x61, 0x0f, 0xae, 0x2f, 0xbc, 0x3f, 0x13, 0x3e, 0x7a,
	0xfd, 0x63, 0xe2, 0x3a, 0x17, 0x13, 0xd7, 0xf9, 0x3d, 0x71, 0x9d, 0x6f, 0x53, 0xb7, 0x76, 0x31,
	0x75, 0x6b, 0xbf, 0xa6, 0x6e, 0xed, 0x7d, 0x8f, 0x27, 0x66, 0x98, 0x46, 0x5e, 0x2c, 0xc7, 0x7e,
	0xb5, 0x8d, 0xe7, 0xd9, 0x17, 0x0b, 0x12, 0x61, 0xca, 0x8d, 0x55, 0xd1, 0x25, 0xdb, 0x1c, 0x6d,
	0xe4, 0x53, 0x7c, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x8c, 0x8f, 0x24, 0xf0, 0x03, 0x00,
	0x00,
}

func (m *MsgUpdateRewardAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRewardAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRewardAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RewardAddr) > 0 {
		i -= len(m.RewardAddr)
		copy(dAtA[i:], m.RewardAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RewardAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateRewardAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateRewardAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateRewardAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateWhitelistedRelayers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateWhitelistedRelayers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateWhitelistedRelayers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Relayers) > 0 {
		for iNdEx := len(m.Relayers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Relayers[iNdEx])
			copy(dAtA[i:], m.Relayers[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Relayers[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateWhitelistedRelayersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateWhitelistedRelayersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateWhitelistedRelayersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *ConsensusMsgUpsertSequencer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsensusMsgUpsertSequencer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsensusMsgUpsertSequencer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Relayers) > 0 {
		for iNdEx := len(m.Relayers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Relayers[iNdEx])
			copy(dAtA[i:], m.Relayers[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Relayers[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RewardAddr) > 0 {
		i -= len(m.RewardAddr)
		copy(dAtA[i:], m.RewardAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.RewardAddr)))
		i--
		dAtA[i] = 0x22
	}
	if m.ConsPubKey != nil {
		{
			size, err := m.ConsPubKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsensusMsgUpsertSequencerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsensusMsgUpsertSequencerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsensusMsgUpsertSequencerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgBumpAccountSequences) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBumpAccountSequences) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBumpAccountSequences) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBumpAccountSequencesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBumpAccountSequencesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBumpAccountSequencesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpgradeDRS) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpgradeDRS) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpgradeDRS) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DrsVersion != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DrsVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpgradeDRSResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpgradeDRSResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpgradeDRSResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateRewardAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RewardAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateRewardAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateWhitelistedRelayers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Relayers) > 0 {
		for _, s := range m.Relayers {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateWhitelistedRelayersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ConsensusMsgUpsertSequencer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ConsPubKey != nil {
		l = m.ConsPubKey.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.RewardAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Relayers) > 0 {
		for _, s := range m.Relayers {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *ConsensusMsgUpsertSequencerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgBumpAccountSequences) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBumpAccountSequencesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpgradeDRS) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DrsVersion != 0 {
		n += 1 + sovTx(uint64(m.DrsVersion))
	}
	return n
}

func (m *MsgUpgradeDRSResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateRewardAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRewardAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRewardAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateRewardAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateRewardAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateRewardAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateWhitelistedRelayers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateWhitelistedRelayers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateWhitelistedRelayers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayers = append(m.Relayers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateWhitelistedRelayersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateWhitelistedRelayersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateWhitelistedRelayersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsensusMsgUpsertSequencer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsensusMsgUpsertSequencer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsensusMsgUpsertSequencer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsPubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsPubKey == nil {
				m.ConsPubKey = &types.Any{}
			}
			if err := m.ConsPubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayers = append(m.Relayers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsensusMsgUpsertSequencerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsensusMsgUpsertSequencerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsensusMsgUpsertSequencerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBumpAccountSequences) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBumpAccountSequences: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBumpAccountSequences: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBumpAccountSequencesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBumpAccountSequencesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBumpAccountSequencesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpgradeDRS) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpgradeDRS: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpgradeDRS: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrsVersion", wireType)
			}
			m.DrsVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DrsVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpgradeDRSResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpgradeDRSResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpgradeDRSResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
