run:
  concurrency: 4
  timeout: 5m
  modules-download-mode: readonly
  # mempool and indexer code is borrowed from Tendermint

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gocyclo

issues:
  exclude-use-default: false
  exclude-files: 
    - da/celestia/mock/server.go
    - ./*_test.go
  exclude-dirs:
    - mempool
    - state/indexer
    - state/txindex