# https://golangci-lint.run/usage/configuration

version: "2"

run:
  concurrency: 4
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    text:
      colors: true
      path: stdout
      print-issued-lines: true
      print-linter-name: true
  path-prefix: ""
  sort-order:
  - file
  - severity
  - linter

linters:
  default: none
  enable:
  - errcheck
  - gocyclo
  - gosec
  - govet
  - ineffassign
  - misspell
  - revive
  - staticcheck
  - unconvert
  - unused
  - errorlint
  exclusions:
    paths:
    # mempool and indexer code is borrowed from Tendermint
    - mempool
    - state/indexer
    - state/txindex
    - da/celestia/mock/server.go
    - ".*_test\\.go" # TODO: bring back
    rules:
    - linters:
      - staticcheck
      text: "^.*SA1019.*$"
    - linters:
      - staticcheck
      text: "^.*QF1008.*$"
    - linters:
      - errcheck
      text: "^.*value of .*it.*Close.* is not checked"
    - linters:
      - gosec
      text: "^.*G115.*$"
      path: ".*_test\\.go$"
  settings:
    revive:
      rules:
      - name: exported
        severity: warning
        disabled: true
    errcheck:
      check-type-assertions: true

issues:
  uniq-by-line: true

formatters:
  enable:
  - goimports
  - gofumpt
  exclusions:
    paths:
    # mempool and indexer code is borrowed from Tendermint
    - mempool
    - state/indexer
    - state/txindex
    - da/celestia/mock/server.go
    - ".*_test\\.go" # TODO: bring back
