with-expecter: true
recursive: true
packages:
  github.com/dymensionxyz/dymint/store:
    interfaces:
      Store:
  github.com/dymensionxyz/dymint/settlement:
    interfaces:
      ClientI:
  github.com/dymensionxyz/dymint/settlement/dymension:
    interfaces:
      CosmosClient:
  github.com/dymensionxyz/dymint/third_party/dymension/sequencer/types:
    interfaces:
      QueryClient:
  github.com/dymensionxyz/dymint/third_party/dymension/rollapp/types:
    interfaces:
      QueryClient:
  github.com/tendermint/tendermint/abci/types:
    interfaces:
      Application:
  github.com/tendermint/tendermint/proxy:
    interfaces:
      AppConnConsensus:
      AppConns:
  github.com/dymensionxyz/dymint/da/celestia/types:
    interfaces:
      CelestiaRPCClient:
  github.com/dymensionxyz/dymint/da/avail:
    interfaces:
     SubstrateApiI:
  github.com/dymensionxyz/dymint/da:
    interfaces:
     DataAvailabilityLayerClient:
  github.com/dymensionxyz/dymint/p2p:
    interfaces:
     GetProposerI:
  
  


