with-expecter: true
packages:
  github.com/dymensionxyz/dymint:
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      LayerI:
        # Modify package-level config for this specific interface (if applicable)
        config: