// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types/dymensionxyz/dymension/sequencer/sequencer.proto

package sequencer

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Sequencer defines a sequencer identified by its' address (sequencerAddress).
// The sequencer could be attached to only one rollapp (rollappId).
type Sequencer struct {
	// Address is the bech32-encoded address of the sequencer account which is the account that the message was sent from.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// DymintPubKey is the public key of the sequencers' dymint client, as a Protobuf Any.
	DymintPubKey *types.Any `protobuf:"bytes,2,opt,name=dymintPubKey,proto3" json:"dymintPubKey,omitempty"`
	// RollappId defines the rollapp to which the sequencer belongs.
	RollappId string `protobuf:"bytes,3,opt,name=rollappId,proto3" json:"rollappId,omitempty"`
	// SequencerMetadata defines the extra information for the sequencer.
	Metadata SequencerMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata"`
	Proposer bool              `protobuf:"varint,6,opt,name=proposer,proto3" json:"proposer,omitempty"` // Deprecated: Do not use.
	// OperatingStatus is the sequencer status (bonded/unbonded).
	Status OperatingStatus `protobuf:"varint,7,opt,name=status,proto3,enum=dymensionxyz.dymension.sequencer.OperatingStatus" json:"status,omitempty"`
	// OptedIn : when true and bonded, the sequencer can be chosen as proposer or successor
	// has no effect if already proposer or successor
	OptedIn bool `protobuf:"varint,14,opt,name=opted_in,json=optedIn,proto3" json:"opted_in,omitempty"`
	// Tokens: A coins which should always be one dym coin. It's the amount of tokens the sequencer has given to the module.
	Tokens github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,8,rep,name=tokens,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"tokens"`
	// NoticePeriodTime defines the time when the sequencer will finish it's notice period. Zero means not started.
	NoticePeriodTime time.Time `protobuf:"bytes,11,opt,name=notice_period_time,json=noticePeriodTime,proto3,stdtime" json:"notice_period_time"`
	// RewardAddr is a bech32 encoded sdk acc address
	RewardAddr string `protobuf:"bytes,12,opt,name=reward_addr,json=rewardAddr,proto3" json:"reward_addr,omitempty"`
	// WhitelistedRelayers is an array of the whitelisted relayer addresses. Addresses are bech32-encoded strings.
	WhitelistedRelayers []string `protobuf:"bytes,13,rep,name=whitelisted_relayers,json=whitelistedRelayers,proto3" json:"whitelisted_relayers,omitempty"`
	// how badly behaved sequencer is, can incur penalties (kicking) when high
	// 0 is good/default, more is worse
	Dishonor uint64 `protobuf:"varint,15,opt,name=dishonor,proto3" json:"dishonor,omitempty"`
}

func (m *Sequencer) Reset()         { *m = Sequencer{} }
func (m *Sequencer) String() string { return proto.CompactTextString(m) }
func (*Sequencer) ProtoMessage()    {}
func (*Sequencer) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c9d1421effe42e1, []int{0}
}
func (m *Sequencer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sequencer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sequencer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sequencer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sequencer.Merge(m, src)
}
func (m *Sequencer) XXX_Size() int {
	return m.Size()
}
func (m *Sequencer) XXX_DiscardUnknown() {
	xxx_messageInfo_Sequencer.DiscardUnknown(m)
}

var xxx_messageInfo_Sequencer proto.InternalMessageInfo

func (m *Sequencer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Sequencer) GetDymintPubKey() *types.Any {
	if m != nil {
		return m.DymintPubKey
	}
	return nil
}

func (m *Sequencer) GetRollappId() string {
	if m != nil {
		return m.RollappId
	}
	return ""
}

func (m *Sequencer) GetMetadata() SequencerMetadata {
	if m != nil {
		return m.Metadata
	}
	return SequencerMetadata{}
}

// Deprecated: Do not use.
func (m *Sequencer) GetProposer() bool {
	if m != nil {
		return m.Proposer
	}
	return false
}

func (m *Sequencer) GetStatus() OperatingStatus {
	if m != nil {
		return m.Status
	}
	return Unbonded
}

func (m *Sequencer) GetOptedIn() bool {
	if m != nil {
		return m.OptedIn
	}
	return false
}

func (m *Sequencer) GetTokens() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *Sequencer) GetNoticePeriodTime() time.Time {
	if m != nil {
		return m.NoticePeriodTime
	}
	return time.Time{}
}

func (m *Sequencer) GetRewardAddr() string {
	if m != nil {
		return m.RewardAddr
	}
	return ""
}

func (m *Sequencer) GetWhitelistedRelayers() []string {
	if m != nil {
		return m.WhitelistedRelayers
	}
	return nil
}

func (m *Sequencer) GetDishonor() uint64 {
	if m != nil {
		return m.Dishonor
	}
	return 0
}

func init() {
	proto.RegisterType((*Sequencer)(nil), "dymensionxyz.dymension.sequencer.Sequencer")
}

func init() {
	proto.RegisterFile("types/dymensionxyz/dymension/sequencer/sequencer.proto", fileDescriptor_0c9d1421effe42e1)
}

var fileDescriptor_0c9d1421effe42e1 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x3f, 0x73, 0xd3, 0x30,
	0x14, 0x8f, 0xdb, 0x34, 0x75, 0x94, 0x52, 0x72, 0x22, 0x83, 0x92, 0x83, 0xc4, 0xc7, 0x31, 0x78,
	0xa9, 0x4d, 0xda, 0x83, 0x8d, 0xa1, 0x61, 0xa1, 0xe5, 0x38, 0x7a, 0x2a, 0x2c, 0x2c, 0x39, 0xd9,
	0x12, 0xae, 0xae, 0xb1, 0x64, 0x24, 0xa5, 0xc5, 0x7c, 0x8a, 0x7e, 0x0e, 0x16, 0x16, 0x3e, 0x44,
	0x8f, 0xa9, 0x23, 0x13, 0xe5, 0xda, 0x2f, 0xc2, 0xd9, 0x96, 0xd3, 0x3f, 0x0c, 0xed, 0x24, 0xbd,
	0xf7, 0x7e, 0xbf, 0xf7, 0xee, 0xfd, 0xf4, 0x13, 0x78, 0x69, 0xf2, 0x8c, 0xe9, 0x90, 0xe6, 0x29,
	0x13, 0x9a, 0x4b, 0xf1, 0x35, 0xff, 0x76, 0x15, 0x84, 0x9a, 0x7d, 0x99, 0x33, 0x11, 0x33, 0x75,
	0x75, 0x0b, 0x32, 0x25, 0x8d, 0x84, 0xde, 0x75, 0x46, 0xb0, 0x08, 0x82, 0x05, 0x6e, 0xd0, 0x8f,
	0xa5, 0x4e, 0xa5, 0x9e, 0x96, 0xf8, 0xb0, 0x0a, 0x2a, 0xf2, 0xa0, 0x9f, 0x48, 0x99, 0xcc, 0x58,
	0x58, 0x46, 0xd1, 0xfc, 0x73, 0x48, 0x44, 0x6e, 0x4b, 0xbd, 0x44, 0x26, 0xb2, 0xa2, 0x14, 0x37,
	0x9b, 0x1d, 0xdd, 0x26, 0x18, 0x9e, 0x32, 0x6d, 0x48, 0x9a, 0x59, 0xc0, 0xb3, 0x6a, 0x8d, 0x6a,
	0x4a, 0x18, 0x11, 0xcd, 0xc2, 0xa3, 0x71, 0xc4, 0x0c, 0x19, 0x87, 0xb1, 0xe4, 0xc2, 0xa2, 0x9e,
	0xdc, 0x40, 0xa5, 0x3a, 0x09, 0x8f, 0xc6, 0xc5, 0x61, 0xcb, 0x2f, 0xee, 0xa9, 0x45, 0xca, 0x0c,
	0xa1, 0xc4, 0x10, 0x4b, 0x7b, 0x75, 0x4f, 0x9a, 0xcc, 0x98, 0x22, 0x86, 0x8b, 0x64, 0xaa, 0x0d,
	0x31, 0x73, 0x2b, 0xc6, 0xd3, 0x1f, 0x2b, 0xa0, 0xbd, 0x5f, 0x83, 0x20, 0x02, 0xab, 0x84, 0x52,
	0xc5, 0xb4, 0x46, 0x8e, 0xe7, 0xf8, 0x6d, 0x5c, 0x87, 0x10, 0x83, 0x35, 0x9a, 0xa7, 0x5c, 0x98,
	0xbd, 0x79, 0xf4, 0x96, 0xe5, 0x68, 0xc9, 0x73, 0xfc, 0xce, 0x66, 0x2f, 0xa8, 0xa4, 0x09, 0x6a,
	0x69, 0x82, 0x6d, 0x91, 0x4f, 0xd0, 0xaf, 0x9f, 0x1b, 0x3d, 0x2b, 0x79, 0xac, 0xf2, 0xcc, 0xc8,
	0xa0, 0x62, 0xe1, 0x1b, 0x3d, 0xe0, 0x63, 0xd0, 0x56, 0x72, 0x36, 0x23, 0x59, 0xb6, 0x43, 0xd1,
	0x72, 0x39, 0xef, 0x2a, 0x01, 0x3f, 0x02, 0xb7, 0x5e, 0x15, 0x35, 0xcb, 0x69, 0x5b, 0xc1, 0x5d,
	0xcf, 0x1e, 0x2c, 0x56, 0x79, 0x67, 0xa9, 0x93, 0xe6, 0xe9, 0x9f, 0x51, 0x03, 0x2f, 0x5a, 0xc1,
	0x21, 0x70, 0x33, 0x25, 0x33, 0xa9, 0x99, 0x42, 0x2d, 0xcf, 0xf1, 0xdd, 0xc9, 0x12, 0x72, 0xf0,
	0x22, 0x07, 0x77, 0x40, 0xab, 0x12, 0x08, 0xad, 0x7a, 0x8e, 0xbf, 0xbe, 0x39, 0xbe, 0x7b, 0xe8,
	0xfb, 0x5a, 0xda, 0xfd, 0x92, 0x88, 0x6d, 0x03, 0xd8, 0x07, 0xae, 0xcc, 0x0c, 0xa3, 0x53, 0x2e,
	0xd0, 0x7a, 0x31, 0x0a, 0xaf, 0x96, 0xf1, 0x8e, 0x80, 0x31, 0x68, 0x19, 0x79, 0xc8, 0x84, 0x46,
	0xae, 0xb7, 0xec, 0x77, 0x36, 0xfb, 0x81, 0xd5, 0xab, 0x30, 0x4f, 0x60, 0xcd, 0x13, 0xbc, 0x96,
	0x5c, 0x4c, 0x9e, 0x17, 0x0b, 0x7c, 0x3f, 0x1f, 0xf9, 0x09, 0x37, 0x07, 0xf3, 0x28, 0x88, 0x65,
	0x5a, 0x7b, 0xa8, 0x3a, 0x36, 0x34, 0x3d, 0x0c, 0x4b, 0x17, 0x94, 0x04, 0x8d, 0x6d, 0x6b, 0x88,
	0x01, 0x14, 0xd2, 0xf0, 0x98, 0x4d, 0x33, 0xa6, 0xb8, 0xa4, 0xd3, 0xc2, 0xb7, 0xa8, 0x53, 0x6a,
	0x39, 0xf8, 0xef, 0xe5, 0x3e, 0xd4, 0xa6, 0x9e, 0xb8, 0xc5, 0xc4, 0x93, 0xf3, 0x91, 0x83, 0xbb,
	0x15, 0x7f, 0xaf, 0xa4, 0x17, 0x00, 0x38, 0x02, 0x1d, 0xc5, 0x8e, 0x89, 0xa2, 0xd3, 0xc2, 0x19,
	0x68, 0xad, 0x7c, 0x35, 0x50, 0xa5, 0xb6, 0x29, 0x55, 0x70, 0x0c, 0x7a, 0xc7, 0x07, 0xdc, 0xb0,
	0x19, 0xd7, 0xc5, 0xea, 0x8a, 0xcd, 0x48, 0xce, 0x94, 0x46, 0x0f, 0xbc, 0x65, 0xbf, 0x8d, 0x1f,
	0x5d, 0xab, 0x61, 0x5b, 0x82, 0x03, 0xe0, 0x52, 0xae, 0x0f, 0xa4, 0x90, 0x0a, 0x3d, 0xf4, 0x1c,
	0xbf, 0x89, 0x17, 0xf1, 0x6e, 0xd3, 0x5d, 0xe9, 0xb6, 0x76, 0x9b, 0x6e, 0xbb, 0x0b, 0x76, 0x9b,
	0x2e, 0xe8, 0x76, 0x26, 0xd1, 0xe9, 0xc5, 0xd0, 0x39, 0xbb, 0x18, 0x3a, 0x7f, 0x2f, 0x86, 0xce,
	0xc9, 0xe5, 0xb0, 0x71, 0x76, 0x39, 0x6c, 0xfc, 0xbe, 0x1c, 0x36, 0x3e, 0xbd, 0xb9, 0xa6, 0xd0,
	0xed, 0xff, 0xc0, 0x85, 0xa9, 0x34, 0x0a, 0xb3, 0xe8, 0xce, 0xcf, 0x12, 0xb5, 0x4a, 0x55, 0xb6,
	0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x69, 0x51, 0xdf, 0x69, 0xa0, 0x04, 0x00, 0x00,
}

func (m *Sequencer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sequencer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sequencer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Dishonor != 0 {
		i = encodeVarintSequencer(dAtA, i, uint64(m.Dishonor))
		i--
		dAtA[i] = 0x78
	}
	if m.OptedIn {
		i--
		if m.OptedIn {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x70
	}
	if len(m.WhitelistedRelayers) > 0 {
		for iNdEx := len(m.WhitelistedRelayers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedRelayers[iNdEx])
			copy(dAtA[i:], m.WhitelistedRelayers[iNdEx])
			i = encodeVarintSequencer(dAtA, i, uint64(len(m.WhitelistedRelayers[iNdEx])))
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.RewardAddr) > 0 {
		i -= len(m.RewardAddr)
		copy(dAtA[i:], m.RewardAddr)
		i = encodeVarintSequencer(dAtA, i, uint64(len(m.RewardAddr)))
		i--
		dAtA[i] = 0x62
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.NoticePeriodTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.NoticePeriodTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintSequencer(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x5a
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSequencer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.Status != 0 {
		i = encodeVarintSequencer(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.Proposer {
		i--
		if m.Proposer {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSequencer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.RollappId) > 0 {
		i -= len(m.RollappId)
		copy(dAtA[i:], m.RollappId)
		i = encodeVarintSequencer(dAtA, i, uint64(len(m.RollappId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.DymintPubKey != nil {
		{
			size, err := m.DymintPubKey.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSequencer(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintSequencer(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSequencer(dAtA []byte, offset int, v uint64) int {
	offset -= sovSequencer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Sequencer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovSequencer(uint64(l))
	}
	if m.DymintPubKey != nil {
		l = m.DymintPubKey.Size()
		n += 1 + l + sovSequencer(uint64(l))
	}
	l = len(m.RollappId)
	if l > 0 {
		n += 1 + l + sovSequencer(uint64(l))
	}
	l = m.Metadata.Size()
	n += 1 + l + sovSequencer(uint64(l))
	if m.Proposer {
		n += 2
	}
	if m.Status != 0 {
		n += 1 + sovSequencer(uint64(m.Status))
	}
	if len(m.Tokens) > 0 {
		for _, e := range m.Tokens {
			l = e.Size()
			n += 1 + l + sovSequencer(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.NoticePeriodTime)
	n += 1 + l + sovSequencer(uint64(l))
	l = len(m.RewardAddr)
	if l > 0 {
		n += 1 + l + sovSequencer(uint64(l))
	}
	if len(m.WhitelistedRelayers) > 0 {
		for _, s := range m.WhitelistedRelayers {
			l = len(s)
			n += 1 + l + sovSequencer(uint64(l))
		}
	}
	if m.OptedIn {
		n += 2
	}
	if m.Dishonor != 0 {
		n += 1 + sovSequencer(uint64(m.Dishonor))
	}
	return n
}

func sovSequencer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSequencer(x uint64) (n int) {
	return sovSequencer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Sequencer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSequencer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sequencer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sequencer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSequencer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DymintPubKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSequencer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSequencer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DymintPubKey == nil {
				m.DymintPubKey = &types.Any{}
			}
			if err := m.DymintPubKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollappId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSequencer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollappId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSequencer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSequencer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Proposer = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= OperatingStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSequencer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSequencer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, types1.Coin{})
			if err := m.Tokens[len(m.Tokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoticePeriodTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSequencer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSequencer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.NoticePeriodTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSequencer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedRelayers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSequencer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSequencer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedRelayers = append(m.WhitelistedRelayers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptedIn", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OptedIn = bool(v != 0)
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dishonor", wireType)
			}
			m.Dishonor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Dishonor |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSequencer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSequencer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSequencer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSequencer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSequencer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSequencer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSequencer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSequencer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSequencer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSequencer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSequencer = fmt.Errorf("proto: unexpected end of group")
)
