# This workflow pushes new grpc da images on every new commit on main.
#
# ghcr.io/dymensionxyz/dymint:latest  
# ghcr.io/dymensionxyz/dymint:{SHORT_SHA} 

name: Push docker images
on:
    push:
        branches:
        - main

permissions:
    contents: read
    packages: write

jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
        - 
          name: Check out the repo
          uses: actions/checkout@v3
        - 
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Create Docker Image Tag for vN.x branch
          run: |
            SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)
            echo "DOCKER_IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV
        - 
          name: Build and push 
          id: build_push_image
          uses: docker/build-push-action@v3
          with:
            file: Dockerfile
            context: .
            push: true
            platforms: linux/amd64
            tags: |
                ghcr.io/dymensionxyz/dymint:latest
                ghcr.io/dymensionxyz/dymint:${{ env.DOCKER_IMAGE_TAG }}