name: Auto Changelog Update

on:
  push:
    branches:
      - main

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate Changelog Update
        run: |
          npm install -g conventional-changelog-cli
          conventional-changelog -p angular -i CHANGELOG.md -s

      - name: Check if "auto-changelog-update" branch exists and update if needed
        id: check_branch
        run: |
          git fetch origin auto-changelog-update:auto-changelog-update --no-tags
          if git rev-parse --verify --quiet auto-changelog-update; then
            echo "::set-output name=branch_exists::true"
            git checkout auto-changelog-update
            git merge main --no-edit
          else
            echo "::set-output name=branch_exists::false"
            git checkout -b auto-changelog-update
          fi

      - name: Create or Update Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update CHANGELOG.md [skip ci]"
          title: "Automated Changelog Update"
          body: "Update the CHANGELOG.md with recent pushes to branch main."
          branch: "auto-changelog-update"  # Static branch name
          delete-branch: true
          branch-suffix: none
      - name: Check if PR needs to be updated
        if: steps.cpr.outputs.pull-request-operation == 'updated'
        run: |
          echo "Changelog PR updated due to new commit to main."
