name: E2E Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:   
  build-rollapp-evm:
    uses: dymensionxyz/rollapp-evm/.github/workflows/build_image_with_dymint.yml@main
    with:
      commit_hash: ${{ github.sha }}

  build-rollapp-wasm:
    uses: dymensionxyz/rollapp-wasm/.github/workflows/build_image_with_dymint.yml@main
    with:
      commit_hash: ${{ github.sha }}

  e2e-tests:
    needs: 
      - build-rollapp-evm
      - build-rollapp-wasm
    uses: dymensionxyz/e2e-tests/.github/workflows/e2e-test-dymint-workflow-call.yml@main
    with:
      rollapp_evm_ci: "e2e"
      rollapp_wasm_ci: "e2e"