name: E2E Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:   
  build-rollapp-evm:
    uses: dymensionxyz/rollapp-evm/.github/workflows/build_image_with_dymint.yml@main
    with:
      commit_hash: ${{ github.sha }}

  build-rollapp-wasm:
    uses: dymensionxyz/rollapp-wasm/.github/workflows/build_image_with_dymint.yml@main
    with:
      commit_hash: ${{ github.sha }}
  
  combine-artifacts:
    needs:
      - build-rollapp-evm
      - build-rollapp-wasm
    runs-on: ubuntu-latest
    steps:
      - name: Download RollApp EVM artifact
        uses: actions/download-artifact@v3
        with:
          name: rollapp-evm

      - name: Download RollApp WASM artifact
        uses: actions/download-artifact@v3
        with:
          name: rollapp-wasm

      - name: Combine Images into e2e.tar
        run: |
          tar -cf /tmp/e2e.tar rollapp-evm.tar rollapp-wasm.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: e2e
          path: /tmp/e2e.tar
          
  e2e-tests:
    needs: combine-artifacts
    uses: dymensionxyz/e2e-tests/.github/workflows/e2e-test-workflow-call.yml@main
    with:
      rollapp_evm_ci: "e2e"
      rollapp_wasm_ci: "e2e"